name: Pull request CI

on: [pull_request]

env:
  NODE_ENV: production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: pnpm i
      - run: pnpm run build
      - run: pnpm test
